### ISSUE TITLE
Question: Egress IPAM operator within Azure

### ISSUE THREAD

**Issue by wouter2397** [redhat-cop/egressip-ipam-operator#51]
Hello,

First of all I would like to thank you for adding Azure support to this operator. We have had plans for quite some time to implement this but had to wait for Azure support.

In the documentation the following is present:
> Differently from AWS, in Azure networks can span multiple AZs and that is the way OCP is installed by default. Currently support for Azure allows you to deploy EgressIPs on the default vnet: `<infra-id>-vnet`

Can you share a bit more information on what's ment by 'the default vnet'?
Within our OpenShift setup we use seperate vnets for our master and worker vm's.
So our vnet name does not meet the `<infra-id>-vnet` that's listed in the documentation.

Does that mean we cannot use this operator in it's current state or am I misinterpreting the documentation?

Thank you in advance!

**Comment by raffaelespazzoli** [comment]
I think you are interpreting it correctly, right now only vanilla IPI is supported. I'd like to improve support but I need better requirements as I don't fully understand Azure network model.
So I assume you do UPI, can you explain you network settings and how you intend to use EgressIPs?

**Comment by wouter2397** [comment]
We deploy OpenShift using IPI.

Our install-config.yaml consists of the following:
```
platform:
  azure:
    region: westeurope
    baseDomainResourceGroupName: <name>
    networkResourceGroupName: <name>
    virtualNetwork: <name>
    controlPlaneSubnet: <name>
    computeSubnet: <name>
```

Our `controlPlaneSubnet `and `computeSubnet `are different, so we can manage them independently.
Does this mean we can just use the vnet we provide in the `controlPlaneSubnet` field?

**Comment by raffaelespazzoli** [comment]
ok, so `<infra-id>-vnet` is the name you get by default. Right now it's hard-coded, but I can look at finding a way to discover it.
Can you share an example of an Infrastructure object and a MachineSet object from one of your cluster created that way?

**Comment by wouter2397** [comment]
It would be really great if you can discover those settings.
I removed all information that is sensitive or related to our organization.
Hopefully you have all the information you need.
If not please let me know.

Based on the MachineSet config from our cluster, I think the following parameters a relevant:
```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
spec:
  template:
    spec:
      providerSpec:
        value:
          networkResourceGroup: <name>
          vnet: <name>
          subnet: <name>
```

Below the full configs

**Infrastructure**:
```
apiVersion: config.openshift.io/v1
kind: Infrastructure
  name: cluster
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    type: Azure
status:
  apiServerInternalURI: '<URL>'
  apiServerURL: '<URL>'
  etcdDiscoveryDomain: <domain>
  infrastructureName: <name>
  platform: Azure
  platformStatus:
    azure:
      cloudName: AzurePublicCloud
      networkResourceGroupName: <name>
      resourceGroupName: <name>
    type: Azure
```

**MachineSet:**
```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: <name>
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: <name>
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 8
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <name>
      machine.openshift.io/cluster-api-machineset: <name>
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <name>
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: <name>
    spec:
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 1024
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: <name>
          userDataSecret:
            name: <name>
          vnet: <name>
          credentialsSecret:
            name: <name>
            namespace: openshift-machine-api
          zone: '1'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: <name>
          kind: AzureMachineProviderSpec
          location: westeurope
          vmSize: Standard_D4s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/...
            sku: ''
            version: ''
          managedIdentity: <name>
          subnet: <name>
          apiVersion: azureproviderconfig.openshift.io/v1beta1
```
