### ISSUE TITLE
AWS: Only subnets referenced by tags are taken into account when determining already used IPs

### ISSUE THREAD

**Issue by zetamorph** [redhat-cop/egressip-ipam-operator#91]
Hi,

I ran into the following issue regarding the AWS controller:

When determining which IPs are already assigned, the operator retrieves the `AWSMachineProviderConfig` to look up the relevant subnets:

https://github.com/redhat-cop/egressip-ipam-operator/blob/2b6acd0f4bedec893dea271d4e6471dcc1582200/controllers/egressipam/aws/aws.go#L294

`AWSMachineProviderConfig` references subnets by one of [ID, Filters, ARN]. However, the operator only checks for subnet references using the following filter: `tag:Name`:

https://github.com/redhat-cop/egressip-ipam-operator/blob/2b6acd0f4bedec893dea271d4e6471dcc1582200/controllers/egressipam/aws/aws.go#L301

In our setup, all subnets are referenced by ID instead of tags. 

```
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: xxxxxxxxxxxxxxxx
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: xxxxxxxx
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: xxxxxxxxxx
      machine.openshift.io/cluster-api-machineset: xxxxxxxx-xxxxx-worker-xxxxx
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
    spec:
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: xxx
          placement:
            availabilityZone: xxx
            region: xxx
          credentialsSecret:
            name: xxxxxx
          instanceType: xxx
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                xxx: xxx
                volumeSize: xxx
                volumeType: xxx
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - xxxxx-xxxx-xxxx-sg
          kind: AWSMachineProviderConfig
          tags:
            [xxx]
          deviceIndex: 0
          ami:
            id: ami-xxxxxxxxxxxxxx
          subnet:
            id: subnet-xxxxxxxx
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: xxxxxxxx
```

Since there are no tag filters, AWS doesn't return anything when calling `DescribeSubnets`. The operator doesn't know that most of the IPs in these subnets are already taken and thus fails to assign egress IPs properly most of the time.
